apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
  - target:
      kind: Deployment
      name: myapp
      version: v1
      group: apps
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Service
      name: myapp-service
      version: v1
    
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8081
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8081