apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
resources:
- ../base

images:
- name: nginx
  newName: nginx_dev
  newTag: "1.20"

commonLabels:
  environment: development
